spring:
  datasource:
    url: jdbc:mysql://mysql:3306/kreamishdb?serverTimezone=UTC
    username: kreamishwas
    password: kreamish
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect