CREATE TABLE BRAND(
    BRAND_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT BRAND_PK PRIMARY KEY (BRAND_ID)
);

CREATE TABLE CATEGORY(
    CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE CATEGORY_DETAIL(
    CATEGORY_DETAIL_ID BIGINT NOT NULL AUTO_INCREMENT,
    CATEGORY_ID BIGINT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT CATEGORY_DETAIL_PK PRIMARY KEY (CATEGORY_DETAIL_ID),
    CONSTRAINT CATEGORY_DETAIL_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

CREATE TABLE ITEM(
    ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CATEGORY_DETAIL_ID BIGINT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    SUB_NAME VARCHAR(200),
    MODEL_CODE VARCHAR(50),
    RELEASE_DATE DATE,
    RELEASE_PRICE BIGINT,
    REPRESENTATIVE_COLOR VARCHAR(50),
    IMAGE_URL VARCHAR(200),
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT ITEM_BRAND_FK FOREIGN KEY (BRAND_ID) REFERENCES BRAND (BRAND_ID),
    CONSTRAINT ITEM_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID),
    CONSTRAINT ITEM_CATEGORY_DETAIL_FK FOREIGN KEY (CATEGORY_DETAIL_ID) REFERENCES CATEGORY_DETAIL (CATEGORY_DETAIL_ID)
);

CREATE TABLE COLLECTION(
    COLLECTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50),
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT COLLECTION_PK PRIMARY KEY (COLLECTION_ID)
);

CREATE TABLE ITEM_COLLECTION_REL(
    ITEM_COLLECTION_REL_ID BIGINT NOT NULL AUTO_INCREMENT,
    ITEM_ID BIGINT NOT NULL,
    COLLECTION_ID BIGINT NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT ITEM_COLLECTION_REL_PK PRIMARY KEY (ITEM_COLLECTION_REL_ID),
    CONSTRAINT ITEM_COLLECTION_REL_ITEM_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
    CONSTRAINT ITEM_COLLECTION_REL_COLLECTION_FK FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(COLLECTION_ID)
);

CREATE TABLE ITEM_SIZES(
    ITEM_SIZES_ID BIGINT NOT NULL AUTO_INCREMENT,
    ITEM_ID BIGINT NOT NULL,
    SIZE VARCHAR(50),
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CREATE_ID VARCHAR(200),
    UPDATE_ID VARCHAR(200),
    CONSTRAINT ITEM_SIZES_PK PRIMARY KEY (ITEM_SIZES_ID),
    CONSTRAINT ITEM_SIZES_ITEM_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
 )